apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-leaf-app
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/argocd-diff-preview
    path: examples/helm-app-of-apps/resources
    targetRevision: HEAD

