apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: example-webhook-validations
webhooks:
  - name: example-validate.example.com
    clientConfig:
      caBundle: "SDFSDGhidfg845234lksdgf08w3j09fFWERTWERT"
    rules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["CREATE", "UPDATE", "LIST"]
        resources: ["deployments"]


