apiVersion: v1
kind: Service
metadata:
  name: app-a
  labels:
    app: app-a
spec:
  selector:
    app: app-a
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP

