apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-a-leaf
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/ben-shaver/argocd-diff-preview
    path: examples/app-of-apps/level-3/a/resources
    targetRevision: HEAD

